apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sound-recorder
  labels:
    app: sound-recorder
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: sound-recorder.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sound-recorder
            port:
              number: 80
  tls:
  - hosts:
    - sound-recorder.example.com
    secretName: sound-recorder-tls
